[package]
name = "kernuxd"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license = "Apache-2.0"
publish = false

[dependencies]
interprocess = { version = "=2.4.4", default-features = false }
kernux-contracts = { path = "../kernux-contracts" }
kernux-policy = { path = "../kernux-policy" }
kernux-store = { path = "../kernux-store" }
serde_json = "=1.0.151"

[lib]
path = "src/lib.rs"
